### ISSUE TITLE
Unsupported media type 415 response code

### ISSUE THREAD

**Issue by Gsantomaggio** [rabbitmq/rabbitmq-management#258]
Executing `hop` tests on master I got the following error in different contexts:

```
./gradlew check -i
....
....
com.rabbitmq.http.client.ClientSpec > PUT /api/cluster-name FAILED
    org.springframework.web.client.HttpClientErrorException: 415 Unsupported Media Type
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91)
        at org.springframework.web.client.RestTemplate.handleResponseError(RestTemplate.java:615)
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:573)
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:544)
        at org.springframework.web.client.RestTemplate.put(RestTemplate.java:393)
        at com.rabbitmq.http.client.Client.setClusterName(Client.java:456)
```

It is the same issue fixed here: https://github.com/rabbitmq/rabbitmq-management/issues/107

should we copy this fix:

```
content_types_accepted(ReqData, Context) ->
   {[{'*', accept_content}], ReqData, Context}.
```
to the other contexts ?

**Comment by michaelklishin** [comment]
@Gsantomaggio sounds good.
