### ISSUE TITLE
rabbitmqadmin not backward compatible with older server versions

### ISSUE THREAD

**Issue by carlhoerberg** [rabbitmq/rabbitmq-management#299]
Using rabbitmqadmin 3.6.4 querying a 3.5.7 server will result in: 

```
Traceback (most recent call last):
  File "/usr/local/sbin/rabbitmqadmin", line 1007, in <module>
    main()
  File "/usr/local/sbin/rabbitmqadmin", line 413, in main
    method()
  File "/usr/local/sbin/rabbitmqadmin", line 592, in invoke_show
    format_list('[{0}]'.format(self.get(uri)), cols, obj_info, self.options)
  File "/usr/local/sbin/rabbitmqadmin", line 436, in get
    return self.http("GET", "%s/api%s" % (self.options.path_prefix, path), "")
  File "/usr/local/sbin/rabbitmqadmin", line 475, in http
    self.options.port)
  File "/usr/local/sbin/rabbitmqadmin", line 451, in __initialize_https_connection
    context = self.__initialize_tls_context())
  File "/usr/local/sbin/rabbitmqadmin", line 467, in __initialize_tls_context
    self.options.ssl_key_file)
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

Is that a known limitation?

**Comment by michaelklishin** [comment]
The only thing I can confidently say from the stack trace is that HTTPS is used. See https://github.com/rabbitmq/rabbitmq-management/issues/225, it involves way more than just RabbitMQ versions.

Just like we don't try to support mismatching `rabbitmqctl` versions, `rabbitmqadmin` is developed together with the HTTP API and supporting older release series is not a goal.

**Comment by carlhoerberg** [comment]
Ok, downloading rabbitmqadmin 3.5.7 worked to query the same server, so I don't think it's https. But fair enough.
