### ISSUE TITLE
Exception if output is piped to external program

### ISSUE THREAD

**Issue by j3pic** [rabbitmq/rabbitmq-management#438]
```
$ rabbitmqadmin list queues|head
+-------------------------------------------+----------+
|                   name                    | messages |
+-------------------------------------------+----------+
| DWH_ETLConsumer.app                       | 0        |
| amq.gen---BNtV4srCWaT-co3kUGbQ            | 0        |
| amq.gen--0LIXQek99OhN9rE7TXq-w            | 0        |
| amq.gen--0Ue3dlYRGllwflqOeku-w            | 0        |
| amq.gen--0Z0sArGO83WRwrDVg_z5g            | 0        |
| amq.gen--3ojbvtlIADHaeDhvNVIng            | 0        |
| amq.gen--62tta3WgG8nv4rfZqT00g            | 0        |
Traceback (most recent call last):
  File "/usr/local/sbin/rabbitmqadmin", line 1012, in <module>
    main()
  File "/usr/local/sbin/rabbitmqadmin", line 413, in main
    method()
  File "/usr/local/sbin/rabbitmqadmin", line 593, in invoke_list
    format_list(self.get(uri), cols, obj_info, self.options)
  File "/usr/local/sbin/rabbitmqadmin", line 710, in format_list
    formatter_instance.display(json_list)
  File "/usr/local/sbin/rabbitmqadmin", line 723, in display
    self.display_list(columns, table)
  File "/usr/local/sbin/rabbitmqadmin", line 821, in display_list
    self.ascii_table(total)
  File "/usr/local/sbin/rabbitmqadmin", line 833, in ascii_table
    self.ascii_row(col_widths, row, "<")
  File "/usr/local/sbin/rabbitmqadmin", line 841, in ascii_row
    output(txt)
  File "/usr/local/sbin/rabbitmqadmin", line 416, in output
    print(s)
IOError: [Errno 32] Broken pipe
```

**Comment by michaelklishin** [comment]
There can be a lot of reasons for "broken UNIX pipes", including target process closing the stream because it was unable to parse it or similar. This is not necessarily an issue in `rabbitmqadmin` which does nothing particularly creative when producing output.
