### ISSUE TITLE
rabbitmqadmin is throwing AttributeError: 'float' object has no attribute 'encode' error.

### ISSUE THREAD

**Issue by JagmohanP** [rabbitmq/rabbitmq-management#457]
While running below command, we are getting **AttributeError: 'float' object has no attribute 'encode' error.**

```
/usr/local/bin/rabbitmqadmin -u "username" -p "password"  list queues name messages message_stats.deliver_get_details.rate
```

```
Traceback (most recent call last):
  File "/usr/local/bin/rabbitmqadmin", line 1012, in <module>
    main()
  File "/usr/local/bin/rabbitmqadmin", line 413, in main
    method()
  File "/usr/local/bin/rabbitmqadmin", line 593, in invoke_list
    format_list(self.get(uri), cols, obj_info, self.options)
  File "/usr/local/bin/rabbitmqadmin", line 710, in format_list
    formatter_instance.display(json_list)
  File "/usr/local/bin/rabbitmqadmin", line 721, in display
    (columns, table) = self.list_to_table(json.loads(json_list), depth)
  File "/usr/local/bin/rabbitmqadmin", line 775, in list_to_table
    add('', 1, item, add_to_row)
  File "/usr/local/bin/rabbitmqadmin", line 742, in add
    add(column, depth + 1, subitem, fun)
  File "/usr/local/bin/rabbitmqadmin", line 742, in add
    add(column, depth + 1, subitem, fun)
  File "/usr/local/bin/rabbitmqadmin", line 754, in add
    fun(column, subitem)
  File "/usr/local/bin/rabbitmqadmin", line 761, in add_to_row
    row[column_ix[col]] = maybe_utf8(val)
  File "/usr/local/bin/rabbitmqadmin", line 431, in maybe_utf8
    return s.encode('utf-8')
AttributeError: 'float' object has no attribute 'encode'
Running | scmb
```

As a workaround we have added below highlighted code. 

``` python
def maybe_utf8(s):
    if isinstance(s, int):
        # s can be also an int for ex messages count
        return str(s)
    if isinstance(s, float):
        # s can be also a float for message rate
        return str(s)
    if sys.version_info[0] == 3:
        # It will have an encoding, which Python will respect
        return s
    else:
        # It won't have an encoding, and Python will pick ASCII by default
        return s.encode('utf-8')
```

**Comment by michaelklishin** [comment]
@JagmohanP looks reasonable. Please submit a PR against the `stable` branch.

**Comment by michaelklishin** [comment]
I applied @JagmohanP's patch manually. It will be in `3.6.11`.
