### ISSUE TITLE
<server>:15672/# on the management page does not load anything

### ISSUE THREAD

**Issue by Jernik** [rabbitmq/rabbitmq-management#51]
When going to the page http://\<server\>:15672/# the screen does not load anything other than the header and the footer. The main div is completely empty, but it does exist. The menu div in the header is also empty, except for the vhost tab. This led to a lot of confusion amongst our team when we were trying to configure RabbitMQ on our machines
![rabbitmq](https://cloud.githubusercontent.com/assets/7637894/9043846/2ce1b5ec-39de-11e5-956f-f7c269b39ac5.PNG)

**Comment by michaelklishin** [comment]
What's in server logs and JavaScript console when that happens?

**Comment by Jernik** [comment]
JS console:
Navigated to http://localhost:15672/
ejs.min.js:1 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.
sammy-0.6.0.min.js:5 [Mon Aug 03 2015 13:19:30 GMT-0500 (Central Daylight Time)] runRoute get 
sammy-0.6.0.min.js:5 [Mon Aug 03 2015 13:19:30 GMT-0500 (Central Daylight Time)] 404 Not Found get   Error: 404 Not Found get  
    at Object.m.Application.g.extend.error (http://localhost:15672/js/sammy-0.6.0.min.js:5:9870)
    at Object.m.Application.g.extend.notFound (http://localhost:15672/js/sammy-0.6.0.min.js:5:9776)
    at Object.m.Application.g.extend.runRoute (http://localhost:15672/js/sammy-0.6.0.min.js:5:8992)
    at Object.m.Application.g.extend._checkLocation (http://localhost:15672/js/sammy-0.6.0.min.js:5:10136)
    at Object.m.Application.g.extend.run (http://localhost:15672/js/sammy-0.6.0.min.js:5:6844)
    at start_app_login (http://localhost:15672/js/main.js:46:9)
    at HTMLDocument.<anonymous> (http://localhost:15672/js/main.js:3:5)
    at Object.f.extend._Deferred.e.resolveWith (http://localhost:15672/js/jquery-1.6.4.min.js:2:15721)
    at Function.e.extend.ready (http://localhost:15672/js/jquery-1.6.4.min.js:2:10657)
    at HTMLDocument.c.addEventListener.C (http://localhost:15672/js/jquery-1.6.4.min.js:2:15177)
sammy-0.6.0.min.js:5 [Mon Aug 03 2015 13:19:30 GMT-0500 (Central Daylight Time)] runRoute get 
sammy-0.6.0.min.js:5 [Mon Aug 03 2015 13:19:30 GMT-0500 (Central Daylight Time)] 404 Not Found get   Error: 404 Not Found get  
    at Object.m.Application.g.extend.error (http://localhost:15672/js/sammy-0.6.0.min.js:5:9870)
    at Object.m.Application.g.extend.notFound (http://localhost:15672/js/sammy-0.6.0.min.js:5:9776)
    at Object.m.Application.g.extend.runRoute (http://localhost:15672/js/sammy-0.6.0.min.js:5:8992)
    at Object.m.Application.g.extend._checkLocation (http://localhost:15672/js/sammy-0.6.0.min.js:5:10136)
    at Object.m.Application.g.extend.run (http://localhost:15672/js/sammy-0.6.0.min.js:5:6844)
    at start_app (http://localhost:15672/js/main.js:88:9)
    at dispatcher_add (http://localhost:15672/js/main.js:9:9)
    at http://localhost:15672/js/dispatcher.js:1:1

RabbitMQ Logs: 
I don't see any recent entries in the log

**Comment by michaelklishin** [comment]
Do you run RabbitMQ behind Apache or Nginx? Something alters URL paths so that standard ones used by the UI are no longer reachable.

MK

**Comment by michaelklishin** [comment]
Closing as UI's inability to access `/api/*` paths very likely suggests an intermediary such as Nginx that performs URL rewriting.
