### ISSUE TITLE
rabbitmqadmin: AttributeError: 'NoneType' object has no attribute 'encode'

### ISSUE THREAD

**Issue by pjmyburg** [rabbitmq/rabbitmq-management#568]
The below command throws **AttributeError: 'NoneType' object has no attribute 'encode'**:

```
./rabbitmqadmin --username=username --password=password  -f long -d 3 list queues
```

```
Traceback (most recent call last):
  File "./rabbitmqadmin", line 1063, in <module>
    main()
  File "./rabbitmqadmin", line 447, in main
    method()
  File "./rabbitmqadmin", line 638, in invoke_list
    format_list(self.get(uri), cols, obj_info, self.options)
  File "./rabbitmqadmin", line 761, in format_list
    formatter_instance.display(json_list)
  File "./rabbitmqadmin", line 772, in display
    (columns, table) = self.list_to_table(json.loads(json_list), depth)
  File "./rabbitmqadmin", line 826, in list_to_table
    add('', 1, item, add_to_row)
  File "./rabbitmqadmin", line 805, in add
    fun(column, subitem)
  File "./rabbitmqadmin", line 812, in add_to_row
    row[column_ix[col]] = maybe_utf8(val)
  File "./rabbitmqadmin", line 468, in maybe_utf8
    return s.encode('utf-8')
AttributeError: 'NoneType' object has no attribute 'encode'
```

We've fixed it locally by updating the _add_to_row_ function to only call _maybe_utf8_ if val is not None:

```
        def add_to_row(col, val):
            if col in column_ix:
                if val: row[column_ix[col]] = maybe_utf8(val)
```

**Comment by michaelklishin** [comment]
This is only the case on Python 2.

**Comment by pjmyburg** [comment]
Has support for Python 2 been dropped?

**Comment by michaelklishin** [comment]
It hasn't but I spent 15 minutes trying to reproduce on Python 3, so this must be mentioned. I am observing test failures, not sure if they are related or due to some leftover data from other runs.

**Comment by michaelklishin** [comment]
I pushed a slightly modified version which I arrived at before this PR was amended. Thank you nonetheless.
