### ISSUE TITLE
rabbitmqadmin should handle 102 Processing status reports introduced in 3.7.16

### ISSUE THREAD

**Issue by volym3ad** [rabbitmq/rabbitmq-management#715]
When trying to import definitions via rabbitmqadmin script (like `rabbitmqadmin import definitions.json`) I'm facing with following exception:
```
Traceback (most recent call last):
  File "/usr/local/bin/rabbitmqadmin", line 1150, in <module>
    main()
  File "/usr/local/bin/rabbitmqadmin", line 494, in main
    method()
  File "/usr/local/bin/rabbitmqadmin", line 688, in invoke_import
    self.post(uri, definitions)
  File "/usr/local/bin/rabbitmqadmin", line 529, in post
    return self.http("POST", "%s/api%s" % (self.options.path_prefix, path), body)
  File "/usr/local/bin/rabbitmqadmin", line 610, in http
    % (resp.status, resp.reason, path, resp.read()))
Exception: Received 102 Processing for path /api/definitions
```
Pretty interesting status code. Though when I'm trying to import definitions via web interface all works fine.
  
* RabbitMQ: 3.7.16
* Erlang: 22
* RabbitMQ server and client application log files
* RabbitMQ plugin information via `rabbitmq-plugins list`

Tell me if more information needed. Thanks in advance.

**Comment by michaelklishin** [comment]
`rabbitmqadmin` was not updated for the periodic 102 updates introduced in https://github.com/rabbitmq/rabbitmq-management/pull/711.

**Comment by michaelklishin** [comment]
@volym3ad note that you can consume [`rabbitmqadmin` from the tip of the `v3.7.x` branch](https://raw.githubusercontent.com/rabbitmq/rabbitmq-management/v3.7.x/bin/rabbitmqadmin) till `3.7.17` ships. It's a standalone zero dependency Python script.

**Comment by volym3ad** [comment]
@michaelklishin thanks a lot! It was super fast 🚀

**Comment by michaelklishin** [comment]
With this change the client in `rabbitmqadmin` will close TCP connection after receiving a `102 Processing`:

```
No.     Time           Source                Destination           Dst port Protocol Length Info
     63 9.121332       127.0.0.1             127.0.0.1             15672    HTTP     4700   POST /api/definitions HTTP/1.1  (application/json)

Frame 63: 4700 bytes on wire (37600 bits), 4700 bytes captured (37600 bits) on interface 0
Null/Loopback
Internet Protocol Version 4, Src: 127.0.0.1, Dst: 127.0.0.1
Transmission Control Protocol, Src Port: 57692, Dst Port: 15672, Seq: 114504, Ack: 1, Len: 4644
[9 Reassembled TCP Segments (119147 bytes): #54(179), #56(16332), #57(16332), #58(16332), #59(16332), #60(16332), #61(16332), #62(16332), #63(4644)]
Hypertext Transfer Protocol
JavaScript Object Notation: application/json

No.     Time           Source                Destination           Dst port Protocol Length Info
     64 9.121351       127.0.0.1             127.0.0.1             57692    TCP      56     15672 → 57692 [ACK] Seq=1 Ack=32844 Win=375424 Len=0 TSval=421419837 TSecr=421419837

Frame 64: 56 bytes on wire (448 bits), 56 bytes captured (448 bits) on interface 0
Null/Loopback
Internet Protocol Version 4, Src: 127.0.0.1, Dst: 127.0.0.1
Transmission Control Protocol, Src Port: 15672, Dst Port: 57692, Seq: 1, Ack: 32844, Len: 0

No.     Time           Source                Destination           Dst port Protocol Length Info
     65 9.121354       127.0.0.1             127.0.0.1             57692    TCP      56     15672 → 57692 [ACK] Seq=1 Ack=65508 Win=342784 Len=0 TSval=421419837 TSecr=421419837

Frame 65: 56 bytes on wire (448 bits), 56 bytes captured (448 bits) on interface 0
Null/Loopback
Internet Protocol Version 4, Src: 127.0.0.1, Dst: 127.0.0.1
Transmission Control Protocol, Src Port: 15672, Dst Port: 57692, Seq: 1, Ack: 65508, Len: 0

No.     Time           Source                Destination           Dst port Protocol Length Info
     66 9.121357       127.0.0.1             127.0.0.1             57692    TCP      56     15672 → 57692 [ACK] Seq=1 Ack=98172 Win=310080 Len=0 TSval=421419837 TSecr=421419837

Frame 66: 56 bytes on wire (448 bits), 56 bytes captured (448 bits) on interface 0
Null/Loopback
Internet Protocol Version 4, Src: 127.0.0.1, Dst: 127.0.0.1
Transmission Control Protocol, Src Port: 15672, Dst Port: 57692, Seq: 1, Ack: 98172, Len: 0

No.     Time           Source                Destination           Dst port Protocol Length Info
     67 9.121359       127.0.0.1             127.0.0.1             57692    TCP      56     15672 → 57692 [ACK] Seq=1 Ack=119148 Win=289152 Len=0 TSval=421419837 TSecr=421419837

Frame 67: 56 bytes on wire (448 bits), 56 bytes captured (448 bits) on interface 0
Null/Loopback
Internet Protocol Version 4, Src: 127.0.0.1, Dst: 127.0.0.1
Transmission Control Protocol, Src Port: 15672, Dst Port: 57692, Seq: 1, Ack: 119148, Len: 0

No.     Time           Source                Destination           Dst port Protocol Length Info
     68 9.131240       127.0.0.1             127.0.0.1             57692    HTTP     131    HTTP/1.1 102 Processing 

Frame 68: 131 bytes on wire (1048 bits), 131 bytes captured (1048 bits) on interface 0
Null/Loopback
Internet Protocol Version 4, Src: 127.0.0.1, Dst: 127.0.0.1
Transmission Control Protocol, Src Port: 15672, Dst Port: 57692, Seq: 1, Ack: 119148, Len: 75
Hypertext Transfer Protocol

No.     Time           Source                Destination           Dst port Protocol Length Info
     69 9.131272       127.0.0.1             127.0.0.1             15672    TCP      56     57692 → 15672 [ACK] Seq=119148 Ack=76 Win=408192 Len=0 TSval=421419847 TSecr=421419847

Frame 69: 56 bytes on wire (448 bits), 56 bytes captured (448 bits) on interface 0
Null/Loopback
Internet Protocol Version 4, Src: 127.0.0.1, Dst: 127.0.0.1
Transmission Control Protocol, Src Port: 57692, Dst Port: 15672, Seq: 119148, Ack: 76, Len: 0

No.     Time           Source                Destination           Dst port Protocol Length Info
     70 9.131785       127.0.0.1             127.0.0.1             15672    TCP      56     57692 → 15672 [FIN, ACK] Seq=119148 Ack=76 Win=408192 Len=0 TSval=421419847 TSecr=421419847

Frame 70: 56 bytes on wire (448 bits), 56 bytes captured (448 bits) on interface 0
Null/Loopback
Internet Protocol Version 4, Src: 127.0.0.1, Dst: 127.0.0.1
Transmission Control Protocol, Src Port: 57692, Dst Port: 15672, Seq: 119148, Ack: 76, Len: 0

No.     Time           Source                Destination           Dst port Protocol Length Info
     71 9.131804       127.0.0.1             127.0.0.1             57692    TCP      56     15672 → 57692 [ACK] Seq=76 Ack=119149 Win=289152 Len=0 TSval=421419847 TSecr=421419847

Frame 71: 56 bytes on wire (448 bits), 56 bytes captured (448 bits) on interface 0
Null/Loopback
Internet Protocol Version 4, Src: 127.0.0.1, Dst: 127.0.0.1
Transmission Control Protocol, Src Port: 15672, Dst Port: 57692, Seq: 76, Ack: 119149, Len: 0

No.     Time           Source                Destination           Dst port Protocol Length Info
     72 9.131836       127.0.0.1             127.0.0.1             57692    TCP      56     15672 → 57692 [FIN, ACK] Seq=76 Ack=119149 Win=289152 Len=0 TSval=421419847 TSecr=421419847

Frame 72: 56 bytes on wire (448 bits), 56 bytes captured (448 bits) on interface 0
Null/Loopback
Internet Protocol Version 4, Src: 127.0.0.1, Dst: 127.0.0.1
Transmission Control Protocol, Src Port: 15672, Dst Port: 57692, Seq: 76, Ack: 119149, Len: 0

No.     Time           Source                Destination           Dst port Protocol Length Info
     73 9.131860       127.0.0.1             127.0.0.1             15672    TCP      56     57692 → 15672 [ACK] Seq=119149 Ack=77 Win=408192 Len=0 TSval=421419847 TSecr=421419847

Frame 73: 56 bytes on wire (448 bits), 56 bytes captured (448 bits) on interface 0
Null/Loopback
Internet Protocol Version 4, Src: 127.0.0.1, Dst: 127.0.0.1
Transmission Control Protocol, Src Port: 57692, Dst Port: 15672, Seq: 119149, Ack: 77, Len: 0
```

which means Cowboy might kill the handler process before it finishes handling the request.

We will have to find another option, possibly disabling `102 Processing` reports as it's proven to be problematic for some clients.

**Comment by michaelklishin** [comment]
#718 disabled `102 Processing` reporting.
