### ISSUE TITLE
TypeError in rabbitmqadmin list queues -f pretty_json

### ISSUE THREAD

**Issue by loop-evgeny** [rabbitmq/rabbitmq-management#794]
RabbitMQ 3.7.24 on Ubuntu 18.04 x64, Python 3.6.9

```
$ rabbitmqadmin list queues -f pretty_json

Traceback (most recent call last):
  File "/usr/local/bin/rabbitmqadmin", line 1150, in <module>
    main()
  File "/usr/local/bin/rabbitmqadmin", line 494, in main
    method()
  File "/usr/local/bin/rabbitmqadmin", line 694, in invoke_list
    format_list(self.get(uri), cols, obj_info, self.options)
  File "/usr/local/bin/rabbitmqadmin", line 826, in format_list
    enc = json.JSONEncoder(False, False, True, True, True, 2)
TypeError: __init__() takes 1 positional argument but 7 were given
```

`-f raw_json` works, however.

**Comment by michaelklishin** [comment]
This did not make it into `3.7.25` but since `rabbitmqadmin` is a zero dependency script, it can be downloaded from GitHub and used with that version or any other.

**Comment by michaelklishin** [comment]
Backported to `v3.8.x` and `v3.7.x` (just in case).

**Comment by lukebakken** [comment]
Thanks @michaelklishin
